services:
#    cwp_user.example:
#        class: Cwp\UserBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
     cwp_voter:
              class: Cwp\UserBundle\Security\Authorization\Voter\CwpVoter
              arguments:
                      entityManager: "@doctrine.orm.entity_manager"
              public: false
              tags:
                    - { name: security.voter }