cwp_util_homepage:
    path:     /hello/{name}
    defaults: { _controller: CwpUtilBundle:Default:index }
cwp_util_addCat:
    path:     /util/index
    defaults: { _controller: CwpUtilBundle:Category:addCat }
cwp_util_forbidden:
    path:     /util/forbidden
    defaults: { _controller: CwpUtilBundle:Backend:forbidden }