## YAML Template.
Cwp\UtilBundle\Entity\BlogCategory:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: name
    properties:
        name:
            - NotBlank: ~
Cwp\UtilBundle\Entity\Menu:
     constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
               fields : name
               message: "节点名称已存在"        
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
               fields : node
               message: "节点路径已存在"
     properties:
            remark:
                  - NotBlank: 
                     message: "最好填一下啦"      
         
            