cwp_admin_homepage:
    path:     /hello/{name}
    defaults: { _controller: CwpAdminBundle:Default:index }

cwp_admin_index:
    path:     /index/index
    defaults: { _controller: CwpAdminBundle:Index:index }

login:
    path:     /login
    defaults: { _controller: CwpAdminBundle:Index:login }

cwp_admin_userlist:
    path:     /userlist
    defaults: { _controller: CwpAdminBundle:User:userlist }

cwp_admin_adduser:
    path:     /adduser
    defaults: { _controller: CwpAdminBundle:User:addUser }
    
cwp_admin_doadduser:
    path:     /doadduser
    defaults: { _controller: CwpAdminBundle:User:doAddUser }
cwp_admin_addcat:
    path:     /addcat
    defaults: { _controller: CwpAdminBundle:Blog:addCat }
cwp_admin_blogcatlist:
    path:     /blogcatlist
    defaults: { _controller: CwpAdminBundle:Blog:catList }
cwp_admin_bloglist:
    path:     /content/blog_list
    defaults: { _controller: CwpAdminBundle:Blog:blogList }
cwp_admin_addblog:
    path:     /content/blog_add
    defaults: { _controller: CwpAdminBundle:Blog:addBlog }
cwp_admin_blogupdate:
    path:     /content/blog_update
    defaults: { _controller: CwpAdminBundle:Blog:blogUpdate }
#菜单管理    
cwp_admin_menulist:
    path:     /user/menu_list
    defaults: { _controller: CwpAdminBundle:Menu:menuList }    
cwp_admin_addmenu:
    path:     /user/menu_add
    defaults: { _controller: CwpAdminBundle:Menu:addMenu }    
cwp_admin_menuupdate:
    path:     /user/menu_update
    defaults: { _controller: CwpAdminBundle:Menu:menuUpdate }
cwp_admin_menudel:
    path:     /user/menu_del
    defaults: { _controller: CwpAdminBundle:Menu:menuDel }  
