index:
    path:     /index
    defaults: { _controller: CwpBlogBundle:Index:index }
cwp_blog_blogread:
    path: /blog/single-{blog_id}
    defaults: { _controller: CwpBlogBundle:Index:blogRead }
    

