Cwp\BlogBundle\Entity\Blog:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: title
    properties:
        title:
            - NotBlank: 
               message: "标题不可为空"
        content:
            - NotBlank: ~
            